test: Add APM agent health test
Co-authored-by: Github Copilot <github.copilot@ai.newrelic.com>

diff --git a/test/k8s-e2e/e2e-apm-fleet-control.yml b/test/k8s-e2e/e2e-apm-fleet-control.yml
--- a/test/k8s-e2e/e2e-apm-fleet-control.yml
+++ b/test/k8s-e2e/e2e-apm-fleet-control.yml
@@ -32,12 +32,25 @@ scenarios:
       - kubectl get all -o wide
       - cd ../../ && tilt down
     tests:
-      nrqls:
-        - query: "SELECT * from K8sPodSample WHERE appName LIKE '${SCENARIO_TAG}-java%' -- comment disabling the appended testKey: "
-        - query: "SELECT * from K8sPodSample WHERE appName LIKE '${SCENARIO_TAG}-python%' -- comment disabling the appended testKey: "
-        - query: "SELECT * from K8sPodSample WHERE appName LIKE '${SCENARIO_TAG}-node%' -- comment disabling the appended testKey: "
-        - query: "SELECT * from K8sPodSample WHERE appName LIKE '${SCENARIO_TAG}-ruby%' -- comment disabling the appended testKey: "
-        - query: "SELECT * from K8sPodSample WHERE appName LIKE '${SCENARIO_TAG}-dotnet%' -- comment disabling the appended testKey: "
-
-
-
+      scripts:
+        - echo 'Hit agent control health endpoint'
+        - POD_NAME=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" | grep 'agent-control')
+        - if [ -z "$POD_NAME" ]; then
+        -  echo "No pod found with name starting with 'agent-control'"
+        -  exit 1
+        - fi
+        - kubectl port-forward pods/${POD_NAME} 51200 &
+        - PORT_FORWARD_PID=$!
+        - sleep 5
+        - response=$(curl -s "http://localhost:51200/status")
+        - for agent in dotnet-agent java-agent node-agent python-agent ruby-agent; do
+        - agent_status=$(echo "$response" | jq -r ".sub_agents[\"${agent}\"].healthy")
+        - if [ "$agent_status" = "true" ]; then
+        -  echo "${agent} is healthy. Success."
+        - else
+        -  echo "${agent} is not healthy. Failing..."
+        -  kill $PORT_FORWARD_PID
+        -  exit 1
+        - fi
+        - done
+        - kill $PORT_FORWARD_PID
