style: remove else clauses

diff --git a/test/k8s-e2e/e2e-apm.yml b/test/k8s-e2e/e2e-apm.yml
--- a/test/k8s-e2e/e2e-apm.yml
+++ b/test/k8s-e2e/e2e-apm.yml
@@ -46,9 +46,8 @@ scenarios:
           if [ -z "$POD_NAME" ]; then
               echo "No pod found with name starting with \"agent-control\""
               exit 1
-          else
-              echo "pod found $POD_NAME"
           fi
+          echo "pod found $POD_NAME"
           kubectl port-forward pods/${POD_NAME} 51200 > /dev/null 2>&1 &
           PORT_FORWARD_PID=$!
           sleep 5
@@ -56,11 +55,10 @@ scenarios:
           echo "response ${response}"
           for agent in dotnet-agent java-agent node-agent python-agent ruby-agent; do
               agent_status=$(echo "$response" | jq -r ".sub_agents[\"${agent}\"].healthy")
-              if [ "$agent_status" = "true" ]; then
-                  echo "${agent} is healthy. Success."
-              else
-                  echo "${agent} is not healthy. Failing..."
-                  exit 1
+              if [ "$agent_status" != "true" ]; then
+                echo "${agent} is not healthy. Failing..."
+                exit 1
               fi
+              echo "${agent} is healthy. Success." 
           done
           kill $PORT_FORWARD_PID
